### ISSUE TITLE
Cropping GeoImages

### ISSUE THREAD

**Issue by lematt1991** [DigitalGlobe/geoio#11]
Would it be possible to add functionality to crop a `GeoImage`?  It would be great if you could specify either the indices of the subset that you would like to crop out or even the bounds in lat/lon coordinates.  Cropping out the data would be trivial, but the projection information would also need to be updated.

**Comment by longbotham** [comment]
passing `return_location=True` to `get_data` or the `iter_xxx` functions should do what you're asking for.  You can then either use the new `geo_transform` info directly in python or write the pixels back to a file on disk with `create_geo_image`.  You can also pass a `geom` directly to `get_data` if you have a single geometry you want to cut to - see the code for `iter_vector` under the example below for details.  

```
import geoio
import dgsamples

vec_str = dgsamples.wv2_longmont_1k_vectors.poly_geojson_utm
img = geoio.DGImage(dgsamples.wv2_longmont_1k.ms)

for x in img.iter_vector(vec_str, return_location=True):
        fname = 'tmp'+'_'.join([str(p) for p in x[1]['upper_left_pixel']])+'.tif'
        dtype = geoio.constants.DICT_NP_TO_GDAL[x[0].dtype]
        geoio.base.create_geo_image(fname,
                                    x[0],
                                    'GTiff',
                                    x[1]['geo_transform'],
                                    img.meta.projection_string,
                                    dtype)
```

**Comment by lematt1991** [comment]
Yep, that's exactly what I was looking for.  Thanks!
