### ISSUE TITLE
iter_vector should return masked numpy array

### ISSUE THREAD

**Issue by kstamatiou** [DigitalGlobe/geoio#2]
Pretty sure it doesn't now, correct?

**Comment by longbotham** [comment]
Agreed, this is a high priority.  I have a catch for such functionality where I currently thing it would be best implemented in [geoio.base.GeoImage](https://github.com/DigitalGlobe/geoio/blob/1d6c26e9d16e5c74eb54a78cd81e0d18beab2b77/geoio/base.py#L284-L288).  This location would change if we decide to implement a geom option in get_data that assumes projections are correctly handled.

**Comment by longbotham** [comment]
Masked arrays are now returned from GeoImage.get_data with a geom, zero-pixels, and out-of-bounds requests.  27687a8dc0f679a5e8f5c79a01c2f199e10ceb61 & 1f9d1a87caabe13c4b105de77bd4e7e21157b5c5
